image: Previous Visual Studio 2017
clone_folder: C:\TBuild\tdesktop
test: off
deploy: off

environment:
  matrix:
   - BUILD_VERSION: disable_crash_reports,disable_autoupdate

install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt TelegramPrivate\custom_api_id.h.enc -secret %api_key_secret%
  - sh: ./appveyor-tools/secure-file -decrypt TelegramPrivate\custom_api_id.h.enc -secret $api_key_secret

matrix:
  fast_finish: true

before_build:
  - .\.appveyor\install.bat

build:
  project: Telegram\Telegram.sln

artifacts:
  - path: out\Debug\Bettergram.exe
    name: BettergramKang.exe
  - path: out\Debug\Bettergram.exe.pdb
    name: BettergramKang.exe.pdb
